[package]
name = "rust-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
chrono = "0.4"
notify-rust = "4.0"
rand = "0.8"
serde = "1.0.201"
